# This file was generated by GoReleaser. DO NOT EDIT.
cask "shanty" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "a372ee434e312fa4f654f08e830e51a468254f67a9da7d1c459241b1f0190bd1"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f61f5974f0262201f8b7d8a55ee22deac37334fed2c8a9c7749055c7b1528a32"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5f853d6f1aab93ae474c88e52f152c71e013f327458beffb1b9ea1bc2194add3"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "20192cfe49f8a90d8e6306ed4fb80bf3b9befa273ea1cdbc4607936380957605"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_linux_amd64.tar.gz"
    end
  end

  name "shanty"
  desc "A terminal client for Navidrome and other Subsonic servers"
  homepage "https://github.com/bspeelm/shanty"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "shanty"
  bash_completion "completions/shanty.bash"
  fish_completion "completions/shanty.fish"
  zsh_completion "completions/_shanty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shanty"]
    end
  end

  # No zap stanza required
end
