# This file was generated by GoReleaser. DO NOT EDIT.
cask "shanty" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "d42f9cf95014bdadca895e037fc42dc057bb25dd6159b29975365aced3ced30f"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "03d1761045a8a3fdd418f73d7ac77d897e0b04dcf5c24db5cdfc6880c0207cc9"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5f4d73e90a24101f7b038b8bbf7ffdf55ddad51afad8be73e171b40034ee8044"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d0d3926e4252672dc527c20bed4d421402d34f69b8dc715f697d9edf9d3eafd8"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_linux_amd64.tar.gz"
    end
  end

  name "shanty"
  desc "A terminal client for Navidrome and other Subsonic servers"
  homepage "https://github.com/bspeelm/shanty"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "shanty"
  bash_completion "completions/shanty.bash"
  fish_completion "completions/shanty.fish"
  zsh_completion "completions/_shanty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shanty"]
    end
  end

  # No zap stanza required
end
