# This file was generated by GoReleaser. DO NOT EDIT.
cask "shanty" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "1d2dd665e91db7c12f85c38b466adeeb2c96a9f61f7b64988d91533be35533ca"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "68304c002f8c561823f5cac6ccb36be3f3db9e7ae0b8ac54ad5a8cd4dbdee5a9"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e3dde3a3d48a1b9a43a5c7c9c4e0728bc75e9dcdf67cc9763ad777f9bbc32fce"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "01a09703b0b9bfaba0e1f5694c4e5d708117d6271daafc6ce5e3becf9b93b704"
      url "https://github.com/bspeelm/shanty/releases/download/v#{version}/shanty_linux_amd64.tar.gz"
    end
  end

  name "shanty"
  desc "A terminal client for Navidrome and other Subsonic servers"
  homepage "https://github.com/bspeelm/shanty"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "shanty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shanty"]
    end
  end

  # No zap stanza required
end
